import Foundation

/// Owns KorpProxy's on-disk state under ~/Library/Application Support/KorpProxy:
/// the engine config.yaml, the auth directory, and logs. Creates a sensible
/// default config (localhost-only, generated management key + API key) on first
/// launch.
final class ConfigStore {
    let baseDir: URL
    let configPath: URL
    let authDir: URL
    let logsDir: URL
    let mgmtKeyPath: URL

    private(set) var port: Int = 8417
    private(set) var managementSecret: String = ""

    init() {
        let support = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? FileManager.default.homeDirectoryForCurrentUser
        baseDir = support.appendingPathComponent("KorpProxy", isDirectory: true)
        configPath = baseDir.appendingPathComponent("config.yaml")
        authDir = baseDir.appendingPathComponent("auths", isDirectory: true)
        logsDir = baseDir.appendingPathComponent("logs", isDirectory: true)
        mgmtKeyPath = baseDir.appendingPathComponent("mgmt-key")

        for dir in [baseDir, authDir, logsDir] {
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        // The management password is app-owned and stable. We deliberately do
        // NOT read it back from config.yaml: the engine rewrites secret-key into
        // a bcrypt hash on startup, which cannot be used as a bearer token. We
        // keep the plaintext here and hand it to the engine via env.
        managementSecret = Self.loadOrCreateToken(at: mgmtKeyPath)
        ensureDefaultConfig()
        loadPort()
    }

    private func ensureDefaultConfig() {
        if FileManager.default.fileExists(atPath: configPath.path) { return }
        let apiKey = Self.randomToken()
        let yaml = """
        # Generated by KorpProxy on first launch. Edit freely.
        host: "127.0.0.1"
        port: 8417
        remote-management:
          allow-remote: false
          secret-key: "\(managementSecret)"
        auth-dir: "\(authDir.path)"
        api-keys:
          - "\(apiKey)"
        debug: false
        logging-to-file: true
        """
        try? yaml.write(to: configPath, atomically: true, encoding: .utf8)
    }

    private func loadPort() {
        guard let text = try? String(contentsOf: configPath, encoding: .utf8) else { return }
        for raw in text.split(whereSeparator: \.isNewline) {
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("port:") {
                let value = line.dropFirst("port:".count).trimmingCharacters(in: .whitespaces)
                if let parsed = Int(value) { port = parsed }
            }
        }
    }

    /// Load a stable app-owned token from `url`, creating it on first use.
    static func loadOrCreateToken(at url: URL) -> String {
        if let existing = try? String(contentsOf: url, encoding: .utf8) {
            let trimmed = existing.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { return trimmed }
        }
        let token = randomToken()
        try? token.write(to: url, atomically: true, encoding: .utf8)
        try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        return token
    }

    static func randomToken() -> String {
        let bytes = (0..<24).map { _ in UInt8.random(in: 0...255) }
        return Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "=", with: "")
    }
}
