import Foundation

/// Owns KorpProxy's on-disk state under ~/Library/Application Support/KorpProxy:
/// the engine config.yaml, the auth directory, and logs. Creates a sensible
/// default config (localhost-only, generated management key + API key) on first
/// launch.
final class ConfigStore {
    let baseDir: URL
    let configPath: URL
    let authDir: URL
    let logsDir: URL

    private(set) var port: Int = 8317
    private(set) var managementSecret: String = ""

    init() {
        let support = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first ?? FileManager.default.homeDirectoryForCurrentUser
        baseDir = support.appendingPathComponent("KorpProxy", isDirectory: true)
        configPath = baseDir.appendingPathComponent("config.yaml")
        authDir = baseDir.appendingPathComponent("auths", isDirectory: true)
        logsDir = baseDir.appendingPathComponent("logs", isDirectory: true)

        for dir in [baseDir, authDir, logsDir] {
            try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        ensureDefaultConfig()
    }

    private func ensureDefaultConfig() {
        if FileManager.default.fileExists(atPath: configPath.path) {
            loadPortAndSecret()
            return
        }
        let secret = Self.randomToken()
        let apiKey = Self.randomToken()
        managementSecret = secret
        let yaml = """
        # Generated by KorpProxy on first launch. Edit freely.
        host: "127.0.0.1"
        port: 8317
        remote-management:
          allow-remote: false
          secret-key: "\(secret)"
        auth-dir: "\(authDir.path)"
        api-keys:
          - "\(apiKey)"
        debug: false
        logging-to-file: true
        """
        try? yaml.write(to: configPath, atomically: true, encoding: .utf8)
    }

    private func loadPortAndSecret() {
        guard let text = try? String(contentsOf: configPath, encoding: .utf8) else { return }
        for raw in text.split(whereSeparator: \.isNewline) {
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("port:") {
                let value = line.dropFirst("port:".count).trimmingCharacters(in: .whitespaces)
                if let parsed = Int(value) { port = parsed }
            } else if line.hasPrefix("secret-key:") {
                let value = line.dropFirst("secret-key:".count)
                    .trimmingCharacters(in: .whitespaces)
                managementSecret = value.trimmingCharacters(in: CharacterSet(charactersIn: "\""))
            }
        }
    }

    static func randomToken() -> String {
        let bytes = (0..<24).map { _ in UInt8.random(in: 0...255) }
        return Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "=", with: "")
    }
}
